CREATE DATABASE burgers
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE burgers;

CREATE TABLE users (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email CHAR(128) NOT NULL UNIQUE,
  user_name CHAR(128) NOT NULL,
  phone CHAR(128) NOT NULL,
  avatar CHAR(128)
);

CREATE TABLE orders (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  contacts CHAR(255)
  description CHAR(255),
  user_id INT(11) NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
);